### ISSUE TITLE
nc: bad address 'xserver'

### ISSUE THREAD

**Issue by ghazel** [dadarek/docker-wait-for-dependencies#2]
If I add a service based on the `suchja/x11server` image, for example:

```
  xserver:
    image: suchja/x11server
    ports:
      - 5900:5900
    environment:
      VNC_PASSWORD: somePW
      XFB_SCREEN: 1280x800x24
```

Then waiting for it as a dependency gives me: `nc: bad address 'xserver'`

**Comment by dadarek** [comment]
Did you add `xserver` as a `depends_on` service of the `start_dependencies` service?

i.e.
```
  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - xserver
    command: xserver:5432
```

If that doesn't work, can you post your entire `docker-compose.yml` please.

**Comment by ghazel** [comment]
Here's a simple example:

```yml
version: '2'
services:
  xserver:
    image: suchja/x11server
    ports:
      - 5900:5900
    environment:
      VNC_PASSWORD: yourPW
      XFB_SCREEN: 1280x800x24

  wine:
    image: suchja/wine:latest
    depends_on:
      - xserver

  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - xserver
    command: xserver:5900
```
